import React,{useMemo,useState}from'react';import{Home,Dumbbell,TrendingUp,User,CalendarDays,Droplets,Moon,Apple,Sparkles,ChevronRight,CheckCircle2,Flame,Plus,HeartPulse,Settings,Target,Trophy}from'lucide-react';
const workouts=[{id:1,title:'Pernas + Glúteos',duration:'45 min',level:'Intermediário',kcal:320,day:'Hoje',progress:70},{id:2,title:'Costas + Bíceps',duration:'50 min',level:'Intermediário',kcal:290,day:'Quarta',progress:0},{id:3,title:'Core + Cardio',duration:'40 min',level:'Moderado',kcal:360,day:'Sexta',progress:0},{id:4,title:'Full Body',duration:'60 min',level:'Intermediário',kcal:410,day:'Domingo',progress:0}];
const habits=[{id:1,label:'Água',detail:'2,0 / 2,5 L',icon:Droplets,done:false},{id:2,label:'Movimento',detail:'8.230 passos',icon:Flame,done:true},{id:3,label:'Proteína',detail:'Meta do dia',icon:Apple,done:true},{id:4,label:'Sono',detail:'7h 42min',icon:Moon,done:true}];
function Logo(){return <div className="brand"><div className="wolf-mark">◖</div><div><div className="brand-title">LOBAS</div><div className="brand-fit">FIT</div></div></div>}
export default function App(){const[tab,setTab]=useState('home');const[hs,setHs]=useState(habits);const completed=hs.filter(h=>h.done).length;const consistency=useMemo(()=>Math.round(completed/hs.length*100),[completed]);const toggle=id=>setHs(x=>x.map(h=>h.id===id?{...h,done:!h.done}:h));
return <div className="app-shell"><main className="phone-frame"><header className="topbar"><Logo/><button className="icon-btn"><Settings size={20}/></button></header>
{tab==='home'&&<section className="screen"><div className="hero"><div><p className="eyebrow">Olá, Loba 🐺</p><h1>Treine como uma loba.</h1><p className="muted">A sua melhor fase começa em você.</p></div><div className="hero-badge"><Sparkles size={18}/></div></div>
<section className="card progress-card"><div><span className="section-label">Seu progresso</span><strong>4/5 treinos</strong><small>Esta semana</small></div><div className="ring" style={{'--p':'80%'}}><span>80%</span></div></section>
<div className="section-heading"><div><span className="section-label">Próximo treino</span><h2>{workouts[0].title}</h2></div><span className="pill">Hoje • 19:00</span></div>
<section className="card workout-feature"><div className="workout-image"><Dumbbell size={42}/></div><div className="workout-copy"><span>{workouts[0].duration} • {workouts[0].level}</span><div className="mini-progress"><div style={{width:workouts[0].progress+'%'}}/></div><button className="primary-btn">Iniciar treino <ChevronRight size={18}/></button></div></section>
<div className="section-heading"><div><span className="section-label">Hábitos</span><h2>Constância do dia</h2></div><strong>{consistency}%</strong></div><div className="habit-grid">{hs.map(h=>{const I=h.icon;return <button key={h.id} className={'habit '+(h.done?'done':'')} onClick={()=>toggle(h.id)}><div className="habit-icon"><I size={20}/></div><strong>{h.label}</strong><span>{h.detail}</span>{h.done&&<CheckCircle2 className="habit-check" size={18}/>}</button>})}</div>
<div className="quick-grid"><button onClick={()=>setTab('workouts')}><Dumbbell/><span>Treinos</span></button><button onClick={()=>setTab('progress')}><TrendingUp/><span>Progresso</span></button><button><CalendarDays/><span>Calendário</span></button><button onClick={()=>setTab('profile')}><User/><span>Perfil</span></button></div></section>}
{tab==='workouts'&&<section className="screen"><div className="page-title"><div><p className="eyebrow">Seu plano</p><h1>Treinos</h1></div><button className="round-plus"><Plus/></button></div><div className="filter-row"><button className="filter active">Em andamento</button><button className="filter">Favoritos</button><button className="filter">Todos</button></div><div className="list">{workouts.map(w=><article className="card workout-row" key={w.id}><div className="workout-thumb"><Dumbbell size={24}/></div><div className="grow"><span className="section-label">{w.day}</span><h3>{w.title}</h3><p>{w.duration} • {w.kcal} kcal</p></div><ChevronRight/></article>)}</div></section>}
{tab==='progress'&&<section className="screen"><div className="page-title"><div><p className="eyebrow">Visão geral</p><h1>Progresso</h1></div><Trophy/></div><div className="stats-grid"><div className="card stat"><strong>12</strong><span>Treinos</span></div><div className="card stat"><strong>420</strong><span>Minutos</span></div><div className="card stat"><strong>3.250</strong><span>kcal</span></div></div><section className="card chart-card"><div className="section-heading"><div><span className="section-label">Evolução</span><h2>Últimas 6 semanas</h2></div><TrendingUp/></div><div className="bars">{[42,58,51,73,66,88,81].map((v,i)=><div key={i}><span style={{height:v}}/></div>)}</div></section><section className="card goal-card"><Target size={26}/><div className="grow"><span className="section-label">Meta semanal</span><h3>5 treinos</h3><p>Você está a 1 treino da meta.</p></div><div className="ring small" style={{'--p':'80%'}}><span>80%</span></div></section></section>}
{tab==='profile'&&<section className="screen"><div className="profile-card"><div className="avatar">L</div><h1>Loba</h1><p>Disciplina, consistência e evolução.</p></div><div className="stats-grid"><div className="card stat"><strong>28</strong><span>Treinos</span></div><div className="card stat"><strong>84</strong><span>Dias ativos</span></div><div className="card stat"><strong>12</strong><span>Semanas</span></div></div><div className="menu-list">{[[User,'Meus dados'],[Target,'Metas'],[HeartPulse,'Medidas'],[Settings,'Preferências']].map(([I,l])=><button className="menu-item" key={l}><I size={20}/><span>{l}</span><ChevronRight size={18}/></button>)}</div></section>}
<nav className="bottom-nav"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/><span>Início</span></button><button className={tab==='workouts'?'active':''} onClick={()=>setTab('workouts')}><Dumbbell/><span>Treinos</span></button><button className={tab==='progress'?'active':''} onClick={()=>setTab('progress')}><TrendingUp/><span>Progresso</span></button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}><User/><span>Perfil</span></button></nav></main></div>}